name: Pipeline 2 - Digital Factory

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v4
      
      - name: SonarCloud Scan
        uses: SonarSource/sonarqube-scan-action@v6
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      
      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS2 }}

      - name: Login to ACR
        run: |
          az acr login --name acrehtp2026

      - name: Build Docker Image
        run: |
          docker build -t pharmalink:latest .
          docker tag pharmalink:latest acrehtp2026.azurecr.io/app:${{ github.sha }}

      - name: Scan Docker Image with Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: pharmalink:latest
          format: table
          exit-code: '1'
          severity: CRITICAL

      - name: Push Docker Image
        run: |
          docker push acrehtp2026.azurecr.io/app:${{ github.sha }}

      - name: Update Web App
        run: |
          az webapp config container set \
            --name app-df-ehttp-emc \
            --resource-group rg-digital-factory \
            --container-image-name acrehtp2026.azurecr.io/app:${{ github.sha }} \
            --container-registry-url https://acrehtp2026.azurecr.io

      - name: Restart Web App
        run: |
          az webapp restart \
            --resource-group rg-digital-factory \
            --name app-df-ehttp-emc
