name: Pipeline 2 - Digital Factory

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:

      # 1. Récupération du code
      - name: Checkout
        uses: actions/checkout@v4
      
      # 2. Analyse qualité SonarCloud
      - name: SonarCloud Scan
        uses: SonarSource/sonarqube-scan-action@v6
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      # 3. Connexion à Azure
      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS2 }}

      # 4. Connexion au registre ACR
      - name: Login to ACR
        run: |
          az acr login --name acrehtp2026 --resource-group rg-digital-factory

      # 5. Build de l’image Docker
      - name: Build Docker Image
        run: |
          docker build -t pharmalink:latest .
          docker tag pharmalink:latest acrehtp2026.azurecr.io/app
