name: Pipeline R&D - PharmaLink DevSecOps

on:
  push:
    branches: [main]

jobs:

  # 1. SECURITY SCAN
  security-scan:
    name: Security Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Safety
        run: pip install safety

      - name: Run Safety (SCA)
        run: safety check || true

      - name: Run Semgrep (SAST)
        uses: returntocorp/semgrep-action@v1
        continue-on-error: true

  # 2. TERRAFORM PROVISIONING
  terraform:
    name: Terraform - Provision Azure
    runs-on: ubuntu-latest
    needs: security-scan

    env:
            TF_PLUGIN_CACHE_DIR: /tmp/.terraform.d/plugin-cache

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.9.8"

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Clean Terraform cache
        run: rm -rf .terraform
        working-directory: Terraform/Rd
        
      - name: Create plugin cache directory
        run: mkdir -p /tmp/.terraform.d/plugin-cache


      - name: Terraform Init
        run: terraform init -upgrade -reconfigure
        working-directory: Terraform/Rd

      - name: Terraform Validate
        run: terraform validate
        working-directory: Terraform/Rd

      - name: Terraform Plan
        run: terraform plan -out=tfplan
        working-directory: Terraform/Rd

      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan
        working-directory: Terraform/Rd

      - name: Get VM Public IP
        run: terraform output -raw vm_public_ip > vm_ip.txt
        working-directory: Terraform/Rd

      - name: Upload VM IP
        uses: actions/upload-artifact@v4
        with:
          name: vm-ip
          path: Terraform/Rd/vm_ip.txt
            # 3. ANSIBLE CONFIGURATION
  ansible:
    name: Ansible - Configure VM
    runs-on: ubuntu-latest
    needs: terraform

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Ansible
        run: pip install ansible

      - name: Download VM IP
        uses: actions/download-artifact@v4
        with:
          name: vm-ip

      - name: Setup SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
      - name: Generate inventory
        run: |
          echo "[vm]" > inventory.ini
          echo "$(cat vm_ip.txt) ansible_user=pharmaadmin ansible_ssh_private_key_file=~/.ssh/id_rsa" >> inventory.ini
      - name: Run Ansible Playbook
        run: ansible-playbook -i inventory.ini configure-ds.yml
        working-directory: Ansible