name: TruffleHog Secrets Scan
on:
  workflow_dispatch:
jobs:
  secrets-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: TruffleHog secrets detection
        uses: trufflesecurity/trufflehog@main
        with:
          path: ./
          extra_args: --only-verified
